TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.05
  max_vel_theta: 1.4
  min_in_place_vel_theta: 0.8
  acc_lim_theta: 2.0
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  holonomic_robot: false

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  meter_scoring: true
  publish_cost_grid_pc: true

  planner_frequency: 1.0
  controller_frequency: 1.0

  base_frame_id: base_link
  global_frame_id: map
  map_frame_id: map
