TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.0
  max_vel_trans: 0.35 # 0.5
  min_vel_trans: 0.0
  max_vel_theta: 2.0
  min_vel_theta: -2.0

  acc_lim_theta: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  holonomic_robot: false

  yaw_goal_tolerance: 3.14159
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  pdist_scale: 0.9
  gdist_scale: 0.9
  occdist_scale: 0.3
  heading_lookahead: 0.5
  heading_scoring: false
  heading_scoring_timestep: 0.8
  meter_scoring: true
  publish_cost_grid_pc: true

  planner_frequency: 0.5
  controller_frequency: 0.5

  base_frame_id: base_link
  global_frame_id: map
  map_frame_id: map


  