TrajectoryPlannerROS:
  max_vel_x: 1.1
  min_vel_x: 0.0
  max_vel_trans: 2.0 # 0.5
  min_vel_trans: 0.0
  max_vel_theta: 0.5
  min_vel_theta: 0.5

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  holonomic_robot: false

  yaw_goal_tolerance: 3.14159
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

#  pdist_scale: 1.5
#  gdist_scale: 1.5
#  occdist_scale: 0.1
#  heading_lookahead: 1.5
#  heading_scoring: true
#  heading_scoring_timestep: 1.0
  meter_scoring: true
  publish_cost_grid_pc: true

#  planner_frequency: 0.0
#  controller_frequency: 30.0

  base_frame_id: base_link
  global_frame_id: map
  map_frame_id: map


  