local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2
  resolution: 0.05
  static_map: False
  rolling_window: true
