TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.4
  min_in_place_vel_theta: 0.8

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05
  latch_xy_goal_tolerance: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  meter_scoring: true
  publish_cost_grid_pc: true
  planner_frequency: 2.0  # Reduce planner frequency if necessary
  controller_frequency: 2.0 # Reduce controller frequency if necessary

  base_frame_id: base_link
  global_frame_id: global_frame

  map_frame_id: map
  map_origin_x: 0.0
  map_origin_y: 0.0

  